export const TABLE_COLUMNS = {
   NAME:{
    key: "name",
    width: "10%",
    sorter: false,
    sortKey: "name",
    align: "left",
    defaultSortOrder: "ascend",
    className: "col-list-name",
    title: <div className="columnTitle">Name</div>,
   },
   DESC:{
    key: "desc",
    width: "10%",
    sorter: false,
    sortKey: "desc",
    align: "left",
    defaultSortOrder: "ascend",
    className: "col-list-name",
    title: <div className="columnTitle">Description</div>,
   },
   START_DATE:{
    key: "start",
    width: "10%",
    sorter: false,
    sortKey: "desc",
    align: "left",
    defaultSortOrder: "ascend",
    className: "col-list-name",
    title: <div className="columnTitle">Start</div>,
   },
   END_DATE:{
    key: "end",
    width: "10%",
    sorter: false,
    sortKey: "desc",
    align: "left",
    defaultSortOrder: "ascend",
    className: "col-list-name",
    title: <div className="columnTitle">End</div>,
   },
   TYPE:{
    key: "type",
    width: "10%",
    sorter: false,
    sortKey: "desc",
    align: "left",
    defaultSortOrder: "ascend",
    className: "col-list-name",
    title: <div className="columnTitle">Type</div>,
   },
   SCOPE:{
    key: "scope",
    width: "10%",
    sorter: false,
    sortKey: "desc",
    align: "left",
    defaultSortOrder: "ascend",
    className: "col-list-name",
    title: <div className="columnTitle">Scope</div>,
   },
   BUDGET_STATUS:{
    key: "status",
    width: "10%",
    sorter: false,
    sortKey: "desc",
    align: "left",
    defaultSortOrder: "ascend",
    className: "col-list-name",
    title: <div className="columnTitle">Budget Status</div>,
   },
   COMMENTS:{
    key: "comments",
    width: "10%",
    sorter: false,
    sortKey: "desc",
    align: "left",
    defaultSortOrder: "ascend",
    className: "col-list-name",
    title: <div className="columnTitle">Comments</div>,
   },
   PERIOD:{
    key: "period",
    width: "10%",
    sorter: false,
    sortKey: "desc",
    align: "left",
    defaultSortOrder: "ascend",
    className: "col-list-name",
    title: <div className="columnTitle">Period</div>,
   },
   ACTION:{
    key: "action",
    width: "10%",
    sorter: false,
    sortKey: "desc",
    align: "left",
    defaultSortOrder: "ascend",
    className: "col-list-name",
    title: <div className="columnTitle">Action</div>,
   },
   EDIT_DELETE:{
    key: "act",
    width: "10%",
    sorter: false,
    sortKey: "desc",
    align: "left",
    defaultSortOrder: "ascend",
    className: "col-list-name",
    title: <div className="columnTitle"></div>,
   }
}